apiVersion: v1
baseDomain: {{YOUR_BASE_DOMAIN}}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      instanceType: {{WORKER_INSTANCE_TYPE}} # Example: Standard_D8s_v5
      resourceGroup: {{YOUR_RESOURCE_GROUP}} # Installer will create if not specified
  replicas: 3
controlPlane:
  architecture: amd4
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      instanceType: {{MASTER_INSTANCE_TYPE}} # Example: Standard_D8s_v5
      resourceGroup: {{YOUR_RESOURCE_GROUP}} # Installer will create if not specified
  replicas: 3
imageContentSources:
- mirrors:
  - {{YOUR_MIRROR_REGISTRY_URL}} # Optional: Add if you use custom mirror registries
  id: cluster-images
installConfig:
  sshKey: {{YOUR_SSH_PUBLIC_KEY}}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: {{YOUR_RESOURCE_GROUP}} # Needed if baseDomain is not a wildcard
    region: {{YOUR_AZURE_REGION}} # Example: eastus
    resourceGroupName: {{YOUR_RESOURCE_GROUP}}
publish: External # Set to 'Internal' if you do not need external access for testing
pullSecret: '{{YOUR_PULL_SECRET}}'
