apiVersion: v1
baseDomain: {{YOUR_BASE_DOMAIN}}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      instanceType: {{WORKER_INSTANCE_TYPE}} # Example: m5.xlarge
      instanceRequirements:
        vcpuCount: 4
        memoryGiB: 16
  replicas: 3
controlPlane:
  architecture: amd4
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      instanceType: {{MASTER_INSTANCE_TYPE}} # Example: m5.xlarge
      instanceRequirements:
        vcpuCount: 4
        memoryGiB: 16
  replicas: 3
imageContentSources:
- mirrors:
  - {{YOUR_MIRROR_REGISTRY_URL}} # Optional: Add if you use custom mirror registries
  id: cluster-images
installConfig:
  sshKey: {{YOUR_SSH_PUBLIC_KEY}}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{YOUR_AWS_REGION}} # Example: us-east-1
publish: External # Set to 'Internal' if you do not need external access for testing
pullSecret: '{{YOUR_PULL_SECRET}}'
